export const nflPlayerList = () => {
  let returnPlayerList = [
    {
      Id: "67474-42669",
      Position: "PF/C",
      "First Name": "Julius",
      Nickname: "Julius Randle",
      "Last Name": "Randle",
      FPPG: 45.714234,
      Played: 17,
      Salary: 8400,
      Game: "LAL@NY",
      Team: "NY",
      Opponent: "LAL",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 9.6,
      Ceiling: 50.2,
      Floor: 37.2,
      BustPct: 27,
      BoomPct: 33.5,
      OwnershipPct: 53.3,
      projminutes: 36.5,
      OptimalPct: 48.8,
    },
    {
      Id: "67474-23825",
      Position: "C",
      "First Name": "Nerlens",
      Nickname: "Nerlens Noel",
      "Last Name": "Noel",
      FPPG: 27,
      Played: 6,
      Salary: 4800,
      Game: "LAL@NY",
      Team: "NY",
      Opponent: "LAL",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 7.8,
      Ceiling: 32.3,
      Floor: 21.8,
      BustPct: 24.3,
      BoomPct: 28,
      OwnershipPct: 23.4,
      projminutes: 29.3,
      OptimalPct: 22.3,
    },
    {
      Id: "67474-55062",
      Position: "C",
      "First Name": "Nikola",
      Nickname: "Nikola Jokic",
      "Last Name": "Jokic",
      FPPG: 53.2,
      Played: 14,
      Salary: 11300,
      Game: "DEN@POR",
      Team: "DEN",
      Opponent: "POR",
      Injury_Indicator: "GTD",
      Injury_Details: "Wrist",
      Tier: "",
      StdDev: 11.4,
      Ceiling: 60.8,
      Floor: 45.5,
      BustPct: 42,
      BoomPct: 25,
      OwnershipPct: 24.6,
      projminutes: 33.3,
      OptimalPct: 34.7,
    },
    {
      Id: "67474-110357",
      Position: "SF/SG",
      "First Name": "RJ",
      Nickname: "RJ Barrett",
      "Last Name": "Barrett",
      FPPG: 30.1,
      Played: 17,
      Salary: 5700,
      Game: "LAL@NY",
      Team: "NY",
      Opponent: "LAL",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 8,
      Ceiling: 35.5,
      Floor: 24.7,
      BustPct: 28.8,
      BoomPct: 24.2,
      OwnershipPct: 30.6,
      projminutes: 35.9,
      OptimalPct: 33.2,
    },
    {
      Id: "67474-14510",
      Position: "SG/SF",
      "First Name": "Alec",
      Nickname: "Alec Burks",
      "Last Name": "Burks",
      FPPG: 25.1,
      Played: 17,
      Salary: 4500,
      Game: "LAL@NY",
      Team: "NY",
      Opponent: "LAL",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 7.4,
      Ceiling: 30.1,
      Floor: 20.1,
      BustPct: 25.5,
      BoomPct: 24.2,
      OwnershipPct: 38.8,
      projminutes: 27.7,
      OptimalPct: 32.8,
    },
    {
      Id: "67474-19067",
      Position: "SG",
      "First Name": "CJ",
      Nickname: "CJ McCollum",
      "Last Name": "McCollum",
      FPPG: 37.8,
      Played: 17,
      Salary: 7600,
      Game: "DEN@POR",
      Team: "POR",
      Opponent: "DEN",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 9.1,
      Ceiling: 43.9,
      Floor: 31.6,
      BustPct: 34.8,
      BoomPct: 23.9,
      OwnershipPct: 31,
      projminutes: 36.3,
      OptimalPct: 37.5,
    },
    {
      Id: "67474-14507",
      Position: "PG",
      "First Name": "Kemba",
      Nickname: "Kemba Walker",
      "Last Name": "Walker",
      FPPG: 26.5,
      Played: 16,
      Salary: 5000,
      Game: "LAL@NY",
      Team: "NY",
      Opponent: "LAL",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 7.5,
      Ceiling: 31.6,
      Floor: 21.4,
      BustPct: 29.8,
      BoomPct: 21.3,
      OwnershipPct: 22.4,
      projminutes: 27.7,
      OptimalPct: 30.3,
    },
    {
      Id: "67474-157807",
      Position: "C",
      "First Name": "Luka",
      Nickname: "Luka Garza",
      "Last Name": "Garza",
      FPPG: 20.3,
      Played: 8,
      Salary: 3500,
      Game: "MIA@DET",
      Team: "DET",
      Opponent: "MIA",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 6.9,
      Ceiling: 24.9,
      Floor: 15.6,
      BustPct: 25.8,
      BoomPct: 21.3,
      OwnershipPct: 1.2,
      projminutes: 21.9,
      OptimalPct: 1.2,
    },
    {
      Id: "67474-20848",
      Position: "PG",
      "First Name": "Damian",
      Nickname: "Damian Lillard",
      "Last Name": "Lillard",
      FPPG: 41.8,
      Played: 16,
      Salary: 8800,
      Game: "DEN@POR",
      Team: "POR",
      Opponent: "DEN",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 9.5,
      Ceiling: 48.3,
      Floor: 35.4,
      BustPct: 40.7,
      BoomPct: 20.8,
      OwnershipPct: 34.3,
      projminutes: 36.3,
      OptimalPct: 34.7,
    },
    {
      Id: "67474-12341",
      Position: "SG/SF",
      "First Name": "Paul",
      Nickname: "Paul George",
      "Last Name": "George",
      FPPG: 42.7,
      Played: 17,
      Salary: 9200,
      Game: "DAL@LAC",
      Team: "LAC",
      Opponent: "DAL",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 9.7,
      Ceiling: 49.2,
      Floor: 36.2,
      BustPct: 44.6,
      BoomPct: 18.5,
      OwnershipPct: 40.1,
      projminutes: 35,
      OptimalPct: 29.3,
    },
    {
      Id: "67474-110337",
      Position: "SG/SF",
      "First Name": "Talen",
      Nickname: "Talen Horton-Tucker",
      "Last Name": "Horton-Tucker",
      FPPG: 29.6,
      Played: 5,
      Salary: 6000,
      Game: "LAL@NY",
      Team: "LAL",
      Opponent: "NY",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 7.9,
      Ceiling: 34.9,
      Floor: 24.2,
      BustPct: 37.4,
      BoomPct: 17.4,
      OwnershipPct: 34.1,
      projminutes: 35,
      OptimalPct: 27.2,
    },
    {
      Id: "67474-145348",
      Position: "SG/PG",
      "First Name": "Immanuel",
      Nickname: "Immanuel Quickley",
      "Last Name": "Quickley",
      FPPG: 22,
      Played: 17,
      Salary: 4100,
      Game: "LAL@NY",
      Team: "NY",
      Opponent: "LAL",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 6.8,
      Ceiling: 26.6,
      Floor: 17.4,
      BustPct: 30.3,
      BoomPct: 17.1,
      OwnershipPct: 32.7,
      projminutes: 25.2,
      OptimalPct: 24.7,
    },
    {
      Id: "67474-14529",
      Position: "PG",
      "First Name": "Cory",
      Nickname: "Cory Joseph",
      "Last Name": "Joseph",
      FPPG: 21.7,
      Played: 16,
      Salary: 4100,
      Game: "MIA@DET",
      Team: "DET",
      Opponent: "MIA",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 6.9,
      Ceiling: 26.3,
      Floor: 17,
      BustPct: 31.9,
      BoomPct: 16.4,
      OwnershipPct: 22.6,
      projminutes: 30.2,
      OptimalPct: 20.3,
    },
    {
      Id: "67474-145328",
      Position: "SF",
      "First Name": "Saddiq",
      Nickname: "Saddiq Bey",
      "Last Name": "Bey",
      FPPG: 27.4,
      Played: 16,
      Salary: 5700,
      Game: "MIA@DET",
      Team: "DET",
      Opponent: "MIA",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 7.7,
      Ceiling: 32.7,
      Floor: 22.2,
      BustPct: 40.8,
      BoomPct: 14.5,
      OwnershipPct: 25.9,
      projminutes: 32.6,
      OptimalPct: 24.2,
    },
    {
      Id: "67474-70827",
      Position: "C",
      "First Name": "Ivica",
      Nickname: "Ivica Zubac",
      "Last Name": "Zubac",
      FPPG: 26.3,
      Played: 17,
      Salary: 5500,
      Game: "DAL@LAC",
      Team: "LAC",
      Opponent: "DAL",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 7.8,
      Ceiling: 31.5,
      Floor: 21.1,
      BustPct: 42,
      BoomPct: 13.8,
      OwnershipPct: 18.1,
      projminutes: 27.1,
      OptimalPct: 11.3,
    },
    {
      Id: "67474-23096",
      Position: "SF/SG",
      "First Name": "Evan",
      Nickname: "Evan Fournier",
      "Last Name": "Fournier",
      FPPG: 22.7,
      Played: 17,
      Salary: 4500,
      Game: "LAL@NY",
      Team: "NY",
      Opponent: "LAL",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 6.9,
      Ceiling: 27.4,
      Floor: 18,
      BustPct: 36.2,
      BoomPct: 13.8,
      OwnershipPct: 19.9,
      projminutes: 28.3,
      OptimalPct: 21.5,
    },
    {
      Id: "67474-80817",
      Position: "C/PF",
      "First Name": "Bam",
      Nickname: "Bam Adebayo",
      "Last Name": "Adebayo",
      FPPG: 35.7,
      Played: 14,
      Salary: 8000,
      Game: "MIA@DET",
      Team: "MIA",
      Opponent: "DET",
      Injury_Indicator: "GTD",
      Injury_Details: "Illness",
      Tier: "",
      StdDev: 9.1,
      Ceiling: 41.9,
      Floor: 29.6,
      BustPct: 51.3,
      BoomPct: 12.9,
      OwnershipPct: 29.9,
      projminutes: 31.2,
      OptimalPct: 22.2,
    },
    {
      Id: "67474-15755",
      Position: "PF/C",
      "First Name": "Anthony",
      Nickname: "Anthony Davis",
      "Last Name": "Davis",
      FPPG: 45.8,
      Played: 18,
      Salary: 10500,
      Game: "LAL@NY",
      Team: "LAL",
      Opponent: "NY",
      Injury_Indicator: "GTD",
      Injury_Details: "Illness",
      Tier: "",
      StdDev: 10.1,
      Ceiling: 52.6,
      Floor: 39,
      BustPct: 55.7,
      BoomPct: 12.8,
      OwnershipPct: 26.7,
      projminutes: 35,
      OptimalPct: 25.2,
    },
    {
      Id: "67474-84669",
      Position: "PG/SG",
      "First Name": "Luka",
      Nickname: "Luka Doncic",
      "Last Name": "Doncic",
      FPPG: 46.1,
      Played: 13,
      Salary: 10700,
      Game: "DAL@LAC",
      Team: "DAL",
      Opponent: "LAC",
      Injury_Indicator: "GTD",
      Injury_Details: "Ankle",
      Tier: "",
      StdDev: 10.2,
      Ceiling: 53,
      Floor: 39.3,
      BustPct: 57.9,
      BoomPct: 11.8,
      OwnershipPct: 10.7,
      projminutes: 34.4,
      OptimalPct: 24,
    },
    {
      Id: "67474-14528",
      Position: "SF/SG",
      "First Name": "Jimmy",
      Nickname: "Jimmy Butler",
      "Last Name": "Butler",
      FPPG: 43.5,
      Played: 14,
      Salary: 10100,
      Game: "MIA@DET",
      Team: "MIA",
      Opponent: "DET",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 10,
      Ceiling: 50.3,
      Floor: 36.8,
      BustPct: 57.6,
      BoomPct: 11.6,
      OwnershipPct: 25.1,
      projminutes: 33.8,
      OptimalPct: 23.8,
    },
    {
      Id: "67474-41594",
      Position: "PF",
      "First Name": "Aaron",
      Nickname: "Aaron Gordon",
      "Last Name": "Gordon",
      FPPG: 27.6,
      Played: 17,
      Salary: 6200,
      Game: "DEN@POR",
      Team: "DEN",
      Opponent: "POR",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 7.8,
      Ceiling: 32.9,
      Floor: 22.4,
      BustPct: 51.4,
      BoomPct: 9.4,
      OwnershipPct: 15.2,
      projminutes: 33.8,
      OptimalPct: 17.2,
    },
    {
      Id: "67474-12355",
      Position: "SG/PG",
      "First Name": "Eric",
      Nickname: "Eric Bledsoe",
      "Last Name": "Bledsoe",
      FPPG: 24.3,
      Played: 17,
      Salary: 5300,
      Game: "DAL@LAC",
      Team: "LAC",
      Opponent: "DAL",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 7.3,
      Ceiling: 29.2,
      Floor: 19.4,
      BustPct: 47.8,
      BoomPct: 9.3,
      OwnershipPct: 15.2,
      projminutes: 30,
      OptimalPct: 20,
    },
    {
      Id: "67474-145339",
      Position: "PF",
      "First Name": "Obi",
      Nickname: "Obi Toppin",
      "Last Name": "Toppin",
      FPPG: 19.4,
      Played: 17,
      Salary: 4100,
      Game: "LAL@NY",
      Team: "NY",
      Opponent: "LAL",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 6.9,
      Ceiling: 24,
      Floor: 14.8,
      BustPct: 44.5,
      BoomPct: 9.3,
      OwnershipPct: 10,
      projminutes: 19.5,
      OptimalPct: 13.7,
    },
    {
      Id: "67474-17333",
      Position: "SG/SF",
      "First Name": "Will",
      Nickname: "Will Barton",
      "Last Name": "Barton",
      FPPG: 28.6,
      Played: 15,
      Salary: 6500,
      Game: "DEN@POR",
      Team: "DEN",
      Opponent: "POR",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 7.9,
      Ceiling: 34,
      Floor: 23.3,
      BustPct: 53.1,
      BoomPct: 9,
      OwnershipPct: 21.2,
      projminutes: 33.3,
      OptimalPct: 15.3,
    },
    {
      Id: "67474-63122",
      Position: "PF/C",
      "First Name": "Kristaps",
      Nickname: "Kristaps Porzingis",
      "Last Name": "Porzingis",
      FPPG: 37.2,
      Played: 11,
      Salary: 8800,
      Game: "DAL@LAC",
      Team: "DAL",
      Opponent: "LAC",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 9.2,
      Ceiling: 43.4,
      Floor: 30.9,
      BustPct: 60.4,
      BoomPct: 8.9,
      OwnershipPct: 20.2,
      projminutes: 30.5,
      OptimalPct: 18.8,
    },
    {
      Id: "67474-110343",
      Position: "SF",
      "First Name": "Nassir",
      Nickname: "Nassir Little",
      "Last Name": "Little",
      FPPG: 19.7,
      Played: 17,
      Salary: 4200,
      Game: "DEN@POR",
      Team: "POR",
      Opponent: "DEN",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 6.8,
      Ceiling: 24.3,
      Floor: 15.1,
      BustPct: 45.5,
      BoomPct: 8.8,
      OwnershipPct: 10.7,
      projminutes: 23.3,
      OptimalPct: 13.2,
    },
    {
      Id: "67474-14523",
      Position: "PG",
      "First Name": "Reggie",
      Nickname: "Reggie Jackson",
      "Last Name": "Jackson",
      FPPG: 26.8,
      Played: 17,
      Salary: 6000,
      Game: "DAL@LAC",
      Team: "LAC",
      Opponent: "DAL",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 7.5,
      Ceiling: 31.8,
      Floor: 21.7,
      BustPct: 51.3,
      BoomPct: 8.6,
      OwnershipPct: 20.8,
      projminutes: 33.6,
      OptimalPct: 12.2,
    },
    {
      Id: "67474-9535",
      Position: "PG",
      "First Name": "Kyle",
      Nickname: "Kyle Lowry",
      "Last Name": "Lowry",
      FPPG: 29.4,
      Played: 15,
      Salary: 6800,
      Game: "MIA@DET",
      Team: "MIA",
      Opponent: "DET",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 8,
      Ceiling: 34.8,
      Floor: 24,
      BustPct: 55.9,
      BoomPct: 8.2,
      OwnershipPct: 17.7,
      projminutes: 33.3,
      OptimalPct: 14.8,
    },
    {
      Id: "67474-157808",
      Position: "PG/SG",
      "First Name": "Cade",
      Nickname: "Cade Cunningham",
      "Last Name": "Cunningham",
      FPPG: 31.9,
      Played: 11,
      Salary: 7500,
      Game: "MIA@DET",
      Team: "DET",
      Opponent: "MIA",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 8.4,
      Ceiling: 37.6,
      Floor: 26.3,
      BustPct: 58.6,
      BoomPct: 8,
      OwnershipPct: 24.3,
      projminutes: 33.5,
      OptimalPct: 20.2,
    },
    {
      Id: "67474-9508",
      Position: "SF/PF",
      "First Name": "Carmelo",
      Nickname: "Carmelo Anthony",
      "Last Name": "Anthony",
      FPPG: 23.7,
      Played: 18,
      Salary: 5400,
      Game: "LAL@NY",
      Team: "LAL",
      Opponent: "NY",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 7.1,
      Ceiling: 28.5,
      Floor: 18.9,
      BustPct: 53.3,
      BoomPct: 6.8,
      OwnershipPct: 14.1,
      projminutes: 29.8,
      OptimalPct: 18.8,
    },
    {
      Id: "67474-40396",
      Position: "PG",
      "First Name": "Monte",
      Nickname: "Monte Morris",
      "Last Name": "Morris",
      FPPG: 21.7,
      Played: 17,
      Salary: 5100,
      Game: "DEN@POR",
      Team: "DEN",
      Opponent: "POR",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 6.9,
      Ceiling: 26.3,
      Floor: 17.1,
      BustPct: 57.2,
      BoomPct: 5.1,
      OwnershipPct: 8.8,
      projminutes: 29.4,
      OptimalPct: 10.5,
    },
    {
      Id: "67474-23831",
      Position: "PF",
      "First Name": "Jerami",
      Nickname: "Jerami Grant",
      "Last Name": "Grant",
      FPPG: 31.5,
      Played: 15,
      Salary: 7800,
      Game: "MIA@DET",
      Team: "DET",
      Opponent: "MIA",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 8.3,
      Ceiling: 37.1,
      Floor: 25.8,
      BustPct: 66.9,
      BoomPct: 5,
      OwnershipPct: 15.2,
      projminutes: 33.4,
      OptimalPct: 12.3,
    },
    {
      Id: "67474-9642",
      Position: "PG",
      "First Name": "Russell",
      Nickname: "Russell Westbrook",
      "Last Name": "Westbrook",
      FPPG: 39.3,
      Played: 18,
      Salary: 9900,
      Game: "LAL@NY",
      Team: "LAL",
      Opponent: "NY",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 9.2,
      Ceiling: 45.5,
      Floor: 33.1,
      BustPct: 71.6,
      BoomPct: 4.8,
      OwnershipPct: 16.4,
      projminutes: 34.9,
      OptimalPct: 14.5,
    },
    {
      Id: "67474-80824",
      Position: "PG",
      "First Name": "Frank",
      Nickname: "Frank Jackson",
      "Last Name": "Jackson",
      FPPG: 16.8,
      Played: 16,
      Salary: 3800,
      Game: "MIA@DET",
      Team: "DET",
      Opponent: "MIA",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 6.1,
      Ceiling: 20.9,
      Floor: 12.7,
      BustPct: 51.8,
      BoomPct: 4.6,
      OwnershipPct: 7.7,
      projminutes: 25.8,
      OptimalPct: 8.8,
    },
    {
      Id: "67474-84717",
      Position: "PG/SG",
      "First Name": "Anfernee",
      Nickname: "Anfernee Simons",
      "Last Name": "Simons",
      FPPG: 16.7,
      Played: 17,
      Salary: 3800,
      Game: "DEN@POR",
      Team: "POR",
      Opponent: "DEN",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 6.2,
      Ceiling: 20.9,
      Floor: 12.5,
      BustPct: 52.5,
      BoomPct: 4.6,
      OwnershipPct: 5.7,
      projminutes: 20.9,
      OptimalPct: 7.5,
    },
    {
      Id: "67474-16293",
      Position: "SF/SG",
      "First Name": "Norman",
      Nickname: "Norman Powell",
      "Last Name": "Powell",
      FPPG: 23.5,
      Played: 15,
      Salary: 5700,
      Game: "DEN@POR",
      Team: "POR",
      Opponent: "DEN",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 7.2,
      Ceiling: 28.3,
      Floor: 18.6,
      BustPct: 62,
      BoomPct: 4.5,
      OwnershipPct: 11.3,
      projminutes: 27.9,
      OptimalPct: 8.5,
    },
    {
      Id: "67474-16196",
      Position: "C/PF",
      "First Name": "Dwight",
      Nickname: "Dwight Powell",
      "Last Name": "Powell",
      FPPG: 17.9,
      Played: 16,
      Salary: 4300,
      Game: "DAL@LAC",
      Team: "DAL",
      Opponent: "LAC",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 6.5,
      Ceiling: 22.3,
      Floor: 13.5,
      BustPct: 58.7,
      BoomPct: 4,
      OwnershipPct: 4.4,
      projminutes: 21.1,
      OptimalPct: 8.7,
    },
    {
      Id: "67474-66196",
      Position: "SG/SF",
      "First Name": "PJ",
      Nickname: "PJ Dozier",
      "Last Name": "Dozier",
      FPPG: 16.3,
      Played: 17,
      Salary: 3800,
      Game: "DEN@POR",
      Team: "DEN",
      Opponent: "POR",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 6.2,
      Ceiling: 20.4,
      Floor: 12.1,
      BustPct: 55.3,
      BoomPct: 4,
      OwnershipPct: 4.9,
      projminutes: 21.3,
      OptimalPct: 5.8,
    },
    {
      Id: "67474-16376",
      Position: "SF/SG",
      "First Name": "Dorian",
      Nickname: "Dorian Finney-Smith",
      "Last Name": "Finney-Smith",
      FPPG: 19.9,
      Played: 16,
      Salary: 4800,
      Game: "DAL@LAC",
      Team: "DAL",
      Opponent: "LAC",
      Injury_Indicator: "",
      Injury_Details: "",
      Tier: "",
      StdDev: 6.6,
      Ceiling: 24.4,
      Floor: 15.5,
      BustPct: 59.9,
      BoomPct: 3.9,
      OwnershipPct: 4.6,
      projminutes: 29.8,
      OptimalPct: 8.3,
    },
    // {
    //   Id: "67474-110312",
    //   Position: "SG/SF",
    //   "First Name": "Tyler",
    //   Nickname: "Tyler Herro",
    //   "Last Name": "Herro",
    //   FPPG: 29,
    //   Played: 16,
    //   Salary: 7600,
    //   Game: "MIA@DET",
    //   Team: "MIA",
    //   Opponent: "DET",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 8,
    //   Ceiling: 34.4,
    //   Floor: 23.7,
    //   BustPct: 74.2,
    //   BoomPct: 2.9,
    //   OwnershipPct: 6,
    //   projminutes: 31.4,
    //   OptimalPct: 9.5,
    // },
    // {
    //   Id: "67474-145547",
    //   Position: "PG",
    //   "First Name": "Facundo",
    //   Nickname: "Facundo Campazzo",
    //   "Last Name": "Campazzo",
    //   FPPG: 15.5,
    //   Played: 16,
    //   Salary: 3800,
    //   Game: "DEN@POR",
    //   Team: "DEN",
    //   Opponent: "POR",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 6,
    //   Ceiling: 19.6,
    //   Floor: 11.5,
    //   BustPct: 60.3,
    //   BoomPct: 2.7,
    //   OwnershipPct: 4,
    //   projminutes: 22.2,
    //   OptimalPct: 2.7,
    // },
    // {
    //   Id: "67474-20491",
    //   Position: "PF/SF",
    //   "First Name": "Robert",
    //   Nickname: "Robert Covington",
    //   "Last Name": "Covington",
    //   FPPG: 19.4,
    //   Played: 17,
    //   Salary: 5000,
    //   Game: "DEN@POR",
    //   Team: "POR",
    //   Opponent: "DEN",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 6.8,
    //   Ceiling: 23.9,
    //   Floor: 14.8,
    //   BustPct: 67.9,
    //   BoomPct: 2.6,
    //   OwnershipPct: 4.8,
    //   projminutes: 25.3,
    //   OptimalPct: 8.7,
    // },
    // {
    //   Id: "67474-9648",
    //   Position: "PF/SF",
    //   "First Name": "Jeff",
    //   Nickname: "Jeff Green",
    //   "Last Name": "Green",
    //   FPPG: 17.6,
    //   Played: 17,
    //   Salary: 4400,
    //   Game: "DEN@POR",
    //   Team: "DEN",
    //   Opponent: "POR",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 6.2,
    //   Ceiling: 21.8,
    //   Floor: 13.4,
    //   BustPct: 64.1,
    //   BoomPct: 2.5,
    //   OwnershipPct: 7.4,
    //   projminutes: 27.2,
    //   OptimalPct: 5.2,
    // },
    // {
    //   Id: "67474-110315",
    //   Position: "SG/SF",
    //   "First Name": "Terance",
    //   Nickname: "Terance Mann",
    //   "Last Name": "Mann",
    //   FPPG: 17.8,
    //   Played: 16,
    //   Salary: 4500,
    //   Game: "DAL@LAC",
    //   Team: "LAC",
    //   Opponent: "DAL",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 6.2,
    //   Ceiling: 22,
    //   Floor: 13.6,
    //   BustPct: 65.1,
    //   BoomPct: 2.3,
    //   OwnershipPct: 7,
    //   projminutes: 26,
    //   OptimalPct: 3.2,
    // },
    // {
    //   Id: "67474-84690",
    //   Position: "PG/SG",
    //   "First Name": "Jalen",
    //   Nickname: "Jalen Brunson",
    //   "Last Name": "Brunson",
    //   FPPG: 26.7,
    //   Played: 16,
    //   Salary: 7200,
    //   Game: "DAL@LAC",
    //   Team: "DAL",
    //   Opponent: "LAC",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 7.6,
    //   Ceiling: 31.8,
    //   Floor: 21.5,
    //   BustPct: 77.5,
    //   BoomPct: 1.9,
    //   OwnershipPct: 6.6,
    //   projminutes: 28.6,
    //   OptimalPct: 5.8,
    // },
    // {
    //   Id: "67474-80816",
    //   Position: "SG",
    //   "First Name": "Malik",
    //   Nickname: "Malik Monk",
    //   "Last Name": "Monk",
    //   FPPG: 17.1,
    //   Played: 18,
    //   Salary: 4400,
    //   Game: "LAL@NY",
    //   Team: "LAL",
    //   Opponent: "NY",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 6,
    //   Ceiling: 21.2,
    //   Floor: 13.1,
    //   BustPct: 67.2,
    //   BoomPct: 1.8,
    //   OwnershipPct: 0.8,
    //   projminutes: 25.4,
    //   OptimalPct: 2.8,
    // },
    // {
    //   Id: "67474-16301",
    //   Position: "C",
    //   "First Name": "Dewayne",
    //   Nickname: "Dewayne Dedmon",
    //   "Last Name": "Dedmon",
    //   FPPG: 12.8,
    //   Played: 17,
    //   Salary: 3700,
    //   Game: "MIA@DET",
    //   Team: "MIA",
    //   Opponent: "DET",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 6.5,
    //   Ceiling: 17.2,
    //   Floor: 8.4,
    //   BustPct: 72.3,
    //   BoomPct: 1.7,
    //   OwnershipPct: 0.1,
    //   projminutes: 12.5,
    //   OptimalPct: 0.5,
    // },
    // {
    //   Id: "67474-85137",
    //   Position: "SG",
    //   "First Name": "Duncan",
    //   Nickname: "Duncan Robinson",
    //   "Last Name": "Robinson",
    //   FPPG: 20,
    //   Played: 17,
    //   Salary: 5500,
    //   Game: "MIA@DET",
    //   Team: "MIA",
    //   Opponent: "DET",
    //   Injury_Indicator: "GTD",
    //   Injury_Details: "Knee",
    //   Tier: "",
    //   StdDev: 6.7,
    //   Ceiling: 24.5,
    //   Floor: 15.5,
    //   BustPct: 76.2,
    //   BoomPct: 1.4,
    //   OwnershipPct: 0.3,
    //   projminutes: 28.4,
    //   OptimalPct: 2.5,
    // },
    // {
    //   Id: "67474-84699",
    //   Position: "SG/SF",
    //   "First Name": "Hamidou",
    //   Nickname: "Hamidou Diallo",
    //   "Last Name": "Diallo",
    //   FPPG: 19.9,
    //   Played: 10,
    //   Salary: 5500,
    //   Game: "MIA@DET",
    //   Team: "DET",
    //   Opponent: "MIA",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 6.8,
    //   Ceiling: 24.5,
    //   Floor: 15.3,
    //   BustPct: 76.3,
    //   BoomPct: 1.4,
    //   OwnershipPct: 1.1,
    //   projminutes: 23.1,
    //   OptimalPct: 3.2,
    // },
    // {
    //   Id: "67474-80809",
    //   Position: "SG",
    //   "First Name": "Josh",
    //   Nickname: "Josh Jackson",
    //   "Last Name": "Jackson",
    //   FPPG: 15.1,
    //   Played: 14,
    //   Salary: 4200,
    //   Game: "MIA@DET",
    //   Team: "DET",
    //   Opponent: "MIA",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 6.2,
    //   Ceiling: 19.3,
    //   Floor: 10.9,
    //   BustPct: 73.1,
    //   BoomPct: 1.3,
    //   OwnershipPct: 0.3,
    //   projminutes: 17.7,
    //   OptimalPct: 3.2,
    // },
    // {
    //   Id: "67474-9957",
    //   Position: "PF/C",
    //   "First Name": "Serge",
    //   Nickname: "Serge Ibaka",
    //   "Last Name": "Ibaka",
    //   FPPG: 14.3,
    //   Played: 3,
    //   Salary: 4200,
    //   Game: "DAL@LAC",
    //   Team: "LAC",
    //   Opponent: "DAL",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 6.6,
    //   Ceiling: 18.7,
    //   Floor: 9.9,
    //   BustPct: 75.9,
    //   BoomPct: 1.3,
    //   OwnershipPct: 0.4,
    //   projminutes: 13.7,
    //   OptimalPct: 2.8,
    // },
    // {
    //   Id: "67474-9561",
    //   Position: "C",
    //   "First Name": "DeAndre",
    //   Nickname: "DeAndre Jordan",
    //   "Last Name": "Jordan",
    //   FPPG: 13.7,
    //   Played: 15,
    //   Salary: 4000,
    //   Game: "LAL@NY",
    //   Team: "LAL",
    //   Opponent: "NY",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 6.4,
    //   Ceiling: 18,
    //   Floor: 9.3,
    //   BustPct: 74.9,
    //   BoomPct: 1.3,
    //   OwnershipPct: 1.1,
    //   projminutes: 13.7,
    //   OptimalPct: 1.5,
    // },
    // {
    //   Id: "67474-58461",
    //   Position: "PF",
    //   "First Name": "Trey",
    //   Nickname: "Trey Lyles",
    //   "Last Name": "Lyles",
    //   FPPG: 13.3,
    //   Played: 16,
    //   Salary: 3700,
    //   Game: "MIA@DET",
    //   Team: "DET",
    //   Opponent: "MIA",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 5.8,
    //   Ceiling: 17.2,
    //   Floor: 9.4,
    //   BustPct: 71.7,
    //   BoomPct: 1.1,
    //   OwnershipPct: 12.3,
    //   projminutes: 15.9,
    //   OptimalPct: 21,
    // },
    // {
    //   Id: "67474-81621",
    //   Position: "PF",
    //   "First Name": "Maxi",
    //   Nickname: "Maxi Kleber",
    //   "Last Name": "Kleber",
    //   FPPG: 14.3,
    //   Played: 7,
    //   Salary: 4100,
    //   Game: "DAL@LAC",
    //   Team: "DAL",
    //   Opponent: "LAC",
    //   Injury_Indicator: "GTD",
    //   Injury_Details: "Oblique",
    //   Tier: "",
    //   StdDev: 5.9,
    //   Ceiling: 18.3,
    //   Floor: 10.4,
    //   BustPct: 75.7,
    //   BoomPct: 0.8,
    //   OwnershipPct: 2.7,
    //   projminutes: 18.8,
    //   OptimalPct: 2.2,
    // },
    // {
    //   Id: "67474-112708",
    //   Position: "SG",
    //   "First Name": "Max",
    //   Nickname: "Max Strus",
    //   "Last Name": "Strus",
    //   FPPG: 13.2,
    //   Played: 12,
    //   Salary: 3900,
    //   Game: "MIA@DET",
    //   Team: "MIA",
    //   Opponent: "DET",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 5.6,
    //   Ceiling: 17,
    //   Floor: 9.5,
    //   BustPct: 78.1,
    //   BoomPct: 0.5,
    //   OwnershipPct: 0.8,
    //   projminutes: 19.7,
    //   OptimalPct: 0.5,
    // },
    // {
    //   Id: "67474-23407",
    //   Position: "PF/C",
    //   "First Name": "P.J.",
    //   Nickname: "P.J. Tucker",
    //   "Last Name": "Tucker",
    //   FPPG: 16.2,
    //   Played: 17,
    //   Salary: 5000,
    //   Game: "MIA@DET",
    //   Team: "MIA",
    //   Opponent: "DET",
    //   Injury_Indicator: "GTD",
    //   Injury_Details: "Illness",
    //   Tier: "",
    //   StdDev: 6.1,
    //   Ceiling: 20.3,
    //   Floor: 12.1,
    //   BustPct: 84.9,
    //   BoomPct: 0.4,
    //   OwnershipPct: 1,
    //   projminutes: 28.3,
    //   OptimalPct: 0.7,
    // },
    // {
    //   Id: "67474-15405",
    //   Position: "PF/C",
    //   "First Name": "JaMychal",
    //   Nickname: "JaMychal Green",
    //   "Last Name": "Green",
    //   FPPG: 12.9,
    //   Played: 17,
    //   Salary: 4200,
    //   Game: "DEN@POR",
    //   Team: "DEN",
    //   Opponent: "POR",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 6.1,
    //   Ceiling: 17,
    //   Floor: 8.8,
    //   BustPct: 83.9,
    //   BoomPct: 0.4,
    //   OwnershipPct: 0.4,
    //   projminutes: 14.2,
    //   OptimalPct: 1,
    // },
    // {
    //   Id: "67474-9660",
    //   Position: "C",
    //   "First Name": "Dwight",
    //   Nickname: "Dwight Howard",
    //   "Last Name": "Howard",
    //   FPPG: 13.1,
    //   Played: 16,
    //   Salary: 4600,
    //   Game: "LAL@NY",
    //   Team: "LAL",
    //   Opponent: "NY",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 6.4,
    //   Ceiling: 17.4,
    //   Floor: 8.8,
    //   BustPct: 88.3,
    //   BoomPct: 0.3,
    //   OwnershipPct: 0.1,
    //   projminutes: 13,
    //   OptimalPct: 0.2,
    // },
    // {
    //   Id: "67474-113267",
    //   Position: "SG/SF",
    //   "First Name": "Caleb",
    //   Nickname: "Caleb Martin",
    //   "Last Name": "Martin",
    //   FPPG: 11.9,
    //   Played: 14,
    //   Salary: 3900,
    //   Game: "MIA@DET",
    //   Team: "MIA",
    //   Opponent: "DET",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 5.6,
    //   Ceiling: 15.7,
    //   Floor: 8.1,
    //   BustPct: 84.3,
    //   BoomPct: 0.3,
    //   OwnershipPct: 0.4,
    //   projminutes: 15.3,
    //   OptimalPct: 1.3,
    // },
    // {
    //   Id: "67474-15691",
    //   Position: "C",
    //   "First Name": "Cody",
    //   Nickname: "Cody Zeller",
    //   "Last Name": "Zeller",
    //   FPPG: 9.8,
    //   Played: 17,
    //   Salary: 3600,
    //   Game: "DEN@POR",
    //   Team: "POR",
    //   Opponent: "DEN",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 5.8,
    //   Ceiling: 13.7,
    //   Floor: 5.9,
    //   BustPct: 86.4,
    //   BoomPct: 0.2,
    //   OwnershipPct: 0.1,
    //   projminutes: 10.2,
    //   OptimalPct: 0.3,
    // },
    // {
    //   Id: "67474-80825",
    //   Position: "PF",
    //   "First Name": "Isaiah",
    //   Nickname: "Isaiah Hartenstein",
    //   "Last Name": "Hartenstein",
    //   FPPG: 11.1,
    //   Played: 16,
    //   Salary: 4800,
    //   Game: "DAL@LAC",
    //   Team: "LAC",
    //   Opponent: "DAL",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 6.5,
    //   Ceiling: 15.5,
    //   Floor: 6.7,
    //   BustPct: 94.6,
    //   BoomPct: 0.1,
    //   OwnershipPct: 0.1,
    //   projminutes: 10,
    //   OptimalPct: 0.3,
    // },
    // {
    //   Id: "67474-15592",
    //   Position: "SG/PG",
    //   "First Name": "Austin",
    //   Nickname: "Austin Rivers",
    //   "Last Name": "Rivers",
    //   FPPG: 11.9,
    //   Played: 15,
    //   Salary: 4200,
    //   Game: "DEN@POR",
    //   Team: "DEN",
    //   Opponent: "POR",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 5.2,
    //   Ceiling: 15.4,
    //   Floor: 8.4,
    //   BustPct: 91.3,
    //   BoomPct: 0.1,
    //   OwnershipPct: 0.1,
    //   projminutes: 22.2,
    //   OptimalPct: 0.3,
    // },
    // {
    //   Id: "67474-9455",
    //   Position: "PG",
    //   "First Name": "Rajon",
    //   Nickname: "Rajon Rondo",
    //   "Last Name": "Rondo",
    //   FPPG: 11.8,
    //   Played: 13,
    //   Salary: 4200,
    //   Game: "LAL@NY",
    //   Team: "LAL",
    //   Opponent: "NY",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 5.6,
    //   Ceiling: 15.5,
    //   Floor: 8,
    //   BustPct: 89.9,
    //   BoomPct: 0.1,
    //   OwnershipPct: 0.1,
    //   projminutes: 13.9,
    //   OptimalPct: 0.5,
    // },
    // {
    //   Id: "67474-12334",
    //   Position: "SG",
    //   "First Name": "Avery",
    //   Nickname: "Avery Bradley",
    //   "Last Name": "Bradley",
    //   FPPG: 10.8,
    //   Played: 17,
    //   Salary: 3600,
    //   Game: "LAL@NY",
    //   Team: "LAL",
    //   Opponent: "NY",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 4.9,
    //   Ceiling: 14.1,
    //   Floor: 7.4,
    //   BustPct: 86.6,
    //   BoomPct: 0.1,
    //   OwnershipPct: 0.2,
    //   projminutes: 23.7,
    //   OptimalPct: 0.3,
    // },
    // {
    //   Id: "67474-9488",
    //   Position: "SF/PF",
    //   "First Name": "LeBron",
    //   Nickname: "LeBron James",
    //   "Last Name": "James",
    //   FPPG: 0,
    //   Played: 8,
    //   Salary: 10000,
    //   Game: "LAL@NY",
    //   Team: "LAL",
    //   Opponent: "NY",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Suspension",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-84682",
    //   Position: "PF/SF",
    //   "First Name": "Michael",
    //   Nickname: "Michael Porter",
    //   "Last Name": "Porter",
    //   FPPG: 0,
    //   Played: 9,
    //   Salary: 5900,
    //   Game: "DEN@POR",
    //   Team: "DEN",
    //   Opponent: "POR",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Back",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-22541",
    //   Position: "C/PF",
    //   "First Name": "Kelly",
    //   Nickname: "Kelly Olynyk",
    //   "Last Name": "Olynyk",
    //   FPPG: 0,
    //   Played: 10,
    //   Salary: 5600,
    //   Game: "MIA@DET",
    //   Team: "DET",
    //   Opponent: "MIA",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Knee",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-15846",
    //   Position: "SG/SF",
    //   "First Name": "Tim",
    //   Nickname: "Tim Hardaway",
    //   "Last Name": "Hardaway",
    //   FPPG: 0,
    //   Played: 16,
    //   Salary: 5600,
    //   Game: "DAL@LAC",
    //   Team: "DAL",
    //   Opponent: "LAC",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-9475",
    //   Position: "PG/SG",
    //   "First Name": "Derrick",
    //   Nickname: "Derrick Rose",
    //   "Last Name": "Rose",
    //   FPPG: 0,
    //   Played: 17,
    //   Salary: 5300,
    //   Game: "LAL@NY",
    //   Team: "NY",
    //   Opponent: "LAL",
    //   Injury_Indicator: "GTD",
    //   Injury_Details: "Ankle",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-84709",
    //   Position: "C",
    //   "First Name": "Mitchell",
    //   Nickname: "Mitchell Robinson",
    //   "Last Name": "Robinson",
    //   FPPG: 0,
    //   Played: 15,
    //   Salary: 5300,
    //   Game: "LAL@NY",
    //   Team: "NY",
    //   Opponent: "LAL",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Concussion",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-9809",
    //   Position: "SF/PF",
    //   "First Name": "Nicolas",
    //   Nickname: "Nicolas Batum",
    //   "Last Name": "Batum",
    //   FPPG: 0,
    //   Played: 14,
    //   Salary: 5100,
    //   Game: "DAL@LAC",
    //   Team: "LAC",
    //   Opponent: "DAL",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Covid-19",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-145307",
    //   Position: "PF",
    //   "First Name": "Isaiah",
    //   Nickname: "Isaiah Stewart",
    //   "Last Name": "Stewart",
    //   FPPG: 0,
    //   Played: 16,
    //   Salary: 5000,
    //   Game: "MIA@DET",
    //   Team: "DET",
    //   Opponent: "MIA",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Suspension",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-14512",
    //   Position: "PF/SF",
    //   "First Name": "Marcus",
    //   Nickname: "Marcus Morris",
    //   "Last Name": "Morris",
    //   FPPG: 0,
    //   Played: 2,
    //   Salary: 4800,
    //   Game: "DAL@LAC",
    //   Team: "LAC",
    //   Opponent: "DAL",
    //   Injury_Indicator: "GTD",
    //   Injury_Details: "Knee",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-145489",
    //   Position: "PG",
    //   "First Name": "Killian",
    //   Nickname: "Killian Hayes",
    //   "Last Name": "Hayes",
    //   FPPG: 0,
    //   Played: 14,
    //   Salary: 4700,
    //   Game: "MIA@DET",
    //   Team: "DET",
    //   Opponent: "MIA",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Thumb",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-15684",
    //   Position: "SG",
    //   "First Name": "Victor",
    //   Nickname: "Victor Oladipo",
    //   "Last Name": "Oladipo",
    //   FPPG: 0,
    //   Played: 33,
    //   Salary: 4500,
    //   Game: "MIA@DET",
    //   Team: "MIA",
    //   Opponent: "DET",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Quadriceps",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-20992",
    //   Position: "PF/SF",
    //   "First Name": "Larry",
    //   Nickname: "Larry Nance",
    //   "Last Name": "Nance",
    //   FPPG: 0,
    //   Played: 17,
    //   Salary: 4400,
    //   Game: "DEN@POR",
    //   Team: "POR",
    //   Opponent: "DEN",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-157834",
    //   Position: "PG",
    //   "First Name": "Bones",
    //   Nickname: "Bones Hyland",
    //   "Last Name": "Hyland",
    //   FPPG: 0,
    //   Played: 14,
    //   Salary: 4400,
    //   Game: "DEN@POR",
    //   Team: "DEN",
    //   Opponent: "POR",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Ankle",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-101329",
    //   Position: "SG/PG",
    //   "First Name": "Kendrick",
    //   Nickname: "Kendrick Nunn",
    //   "Last Name": "Nunn",
    //   FPPG: 0,
    //   Played: 60,
    //   Salary: 4400,
    //   Game: "LAL@NY",
    //   Team: "LAL",
    //   Opponent: "NY",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Knee",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-9538",
    //   Position: "PF",
    //   "First Name": "Trevor",
    //   Nickname: "Trevor Ariza",
    //   "Last Name": "Ariza",
    //   FPPG: 0,
    //   Played: 34,
    //   Salary: 4200,
    //   Game: "LAL@NY",
    //   Team: "LAL",
    //   Opponent: "NY",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Ankle",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-101387",
    //   Position: "PG",
    //   "First Name": "Gabe",
    //   Nickname: "Gabe Vincent",
    //   "Last Name": "Vincent",
    //   FPPG: 1.6,
    //   Played: 14,
    //   Salary: 4000,
    //   Game: "MIA@DET",
    //   Team: "MIA",
    //   Opponent: "DET",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 1.1,
    //   Ceiling: 2.3,
    //   Floor: 0.9,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 2.4,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-157805",
    //   Position: "SG",
    //   "First Name": "Brandon",
    //   Nickname: "Brandon Boston",
    //   "Last Name": "Boston",
    //   FPPG: 0,
    //   Played: 7,
    //   Salary: 3900,
    //   Game: "DAL@LAC",
    //   Team: "LAC",
    //   Opponent: "DAL",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-80813",
    //   Position: "PG",
    //   "First Name": "Frank",
    //   Nickname: "Frank Ntilikina",
    //   "Last Name": "Ntilikina",
    //   FPPG: 0,
    //   Played: 15,
    //   Salary: 3900,
    //   Game: "DAL@LAC",
    //   Team: "DAL",
    //   Opponent: "LAC",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Calf",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-9481",
    //   Position: "C",
    //   "First Name": "Taj",
    //   Nickname: "Taj Gibson",
    //   "Last Name": "Gibson",
    //   FPPG: 0,
    //   Played: 10,
    //   Salary: 3800,
    //   Game: "LAL@NY",
    //   Team: "NY",
    //   Opponent: "LAL",
    //   Injury_Indicator: "GTD",
    //   Injury_Details: "Groin",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-40262",
    //   Position: "SG",
    //   "First Name": "Sterling",
    //   Nickname: "Sterling Brown",
    //   "Last Name": "Brown",
    //   FPPG: 6.6,
    //   Played: 14,
    //   Salary: 3800,
    //   Game: "DAL@LAC",
    //   Team: "DAL",
    //   Opponent: "LAC",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 4.4,
    //   Ceiling: 9.6,
    //   Floor: 3.6,
    //   BustPct: 99.2,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 9.4,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-19781",
    //   Position: "SF/SG",
    //   "First Name": "Kent",
    //   Nickname: "Kent Bazemore",
    //   "Last Name": "Bazemore",
    //   FPPG: 0.9,
    //   Played: 16,
    //   Salary: 3700,
    //   Game: "LAL@NY",
    //   Team: "LAL",
    //   Opponent: "NY",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0.6,
    //   Ceiling: 1.3,
    //   Floor: 0.5,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 1.6,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-15843",
    //   Position: "PG/SG",
    //   "First Name": "Trey",
    //   Nickname: "Trey Burke",
    //   "Last Name": "Burke",
    //   FPPG: 7.5,
    //   Played: 7,
    //   Salary: 3700,
    //   Game: "DAL@LAC",
    //   Team: "DAL",
    //   Opponent: "LAC",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 4.7,
    //   Ceiling: 10.6,
    //   Floor: 4.3,
    //   BustPct: 97.5,
    //   BoomPct: 0,
    //   OwnershipPct: 0.1,
    //   projminutes: 10,
    //   OptimalPct: 0.1,
    // },
    // {
    //   Id: "67474-17517",
    //   Position: "SF/SG",
    //   "First Name": "Tony",
    //   Nickname: "Tony Snell",
    //   "Last Name": "Snell",
    //   FPPG: 5.6,
    //   Played: 11,
    //   Salary: 3600,
    //   Game: "DEN@POR",
    //   Team: "POR",
    //   Opponent: "DEN",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 3.7,
    //   Ceiling: 8.1,
    //   Floor: 3.1,
    //   BustPct: 99.8,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 10.8,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-111492",
    //   Position: "PF",
    //   "First Name": "Amir",
    //   Nickname: "Amir Coffey",
    //   "Last Name": "Coffey",
    //   FPPG: 6.3,
    //   Played: 13,
    //   Salary: 3600,
    //   Game: "DAL@LAC",
    //   Team: "LAC",
    //   Opponent: "DAL",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 4,
    //   Ceiling: 8.9,
    //   Floor: 3.6,
    //   BustPct: 99.4,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 11.1,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-14511",
    //   Position: "PF/SF",
    //   "First Name": "Markieff",
    //   Nickname: "Markieff Morris",
    //   "Last Name": "Morris",
    //   FPPG: 0,
    //   Played: 10,
    //   Salary: 3600,
    //   Game: "MIA@DET",
    //   Team: "MIA",
    //   Opponent: "DET",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Neck",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-158136",
    //   Position: "SG",
    //   "First Name": "Austin",
    //   Nickname: "Austin Reaves",
    //   "Last Name": "Reaves",
    //   FPPG: 0,
    //   Played: 10,
    //   Salary: 3600,
    //   Game: "LAL@NY",
    //   Team: "LAL",
    //   Opponent: "NY",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Hamstring",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-9956",
    //   Position: "SG",
    //   "First Name": "Wayne",
    //   Nickname: "Wayne Ellington",
    //   "Last Name": "Ellington",
    //   FPPG: 7.5,
    //   Played: 10,
    //   Salary: 3600,
    //   Game: "LAL@NY",
    //   Team: "LAL",
    //   Opponent: "NY",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 4.1,
    //   Ceiling: 10.3,
    //   Floor: 4.7,
    //   BustPct: 98.3,
    //   BoomPct: 0,
    //   OwnershipPct: 0.1,
    //   projminutes: 14.2,
    //   OptimalPct: 0.1,
    // },
    // {
    //   Id: "67474-23823",
    //   Position: "C/PF",
    //   "First Name": "Willie",
    //   Nickname: "Willie Cauley-Stein",
    //   "Last Name": "Cauley-Stein",
    //   FPPG: 1,
    //   Played: 16,
    //   Salary: 3500,
    //   Game: "DAL@LAC",
    //   Team: "DAL",
    //   Opponent: "LAC",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0.6,
    //   Ceiling: 1.4,
    //   Floor: 0.5,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 1.4,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-117285",
    //   Position: "SF",
    //   "First Name": "Vlatko",
    //   Nickname: "Vlatko Cancar",
    //   "Last Name": "Cancar",
    //   FPPG: 0,
    //   Played: 46,
    //   Salary: 3500,
    //   Game: "DEN@POR",
    //   Team: "DEN",
    //   Opponent: "POR",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-117286",
    //   Position: "C",
    //   "First Name": "Moses",
    //   Nickname: "Moses Brown",
    //   "Last Name": "Brown",
    //   FPPG: 1.5,
    //   Played: 6,
    //   Salary: 3500,
    //   Game: "DAL@LAC",
    //   Team: "DAL",
    //   Opponent: "LAC",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 1,
    //   Ceiling: 2.1,
    //   Floor: 0.8,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 1.4,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-110640",
    //   Position: "PF",
    //   "First Name": "Luka",
    //   Nickname: "Luka Samanic",
    //   "Last Name": "Samanic",
    //   FPPG: 0,
    //   Played: 33,
    //   Salary: 3500,
    //   Game: "LAL@NY",
    //   Team: "NY",
    //   Opponent: "LAL",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-117821",
    //   Position: "PG/SG",
    //   "First Name": "Keljin",
    //   Nickname: "Keljin Blevins",
    //   "Last Name": "Blevins",
    //   FPPG: 0.7,
    //   Played: 19,
    //   Salary: 3500,
    //   Game: "DEN@POR",
    //   Team: "POR",
    //   Opponent: "DEN",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0.4,
    //   Ceiling: 1,
    //   Floor: 0.4,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 1.6,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-66108",
    //   Position: "PG/SG",
    //   "First Name": "Jamal",
    //   Nickname: "Jamal Murray",
    //   "Last Name": "Murray",
    //   FPPG: 0,
    //   Played: 48,
    //   Salary: 3500,
    //   Game: "DEN@POR",
    //   Team: "DEN",
    //   Opponent: "POR",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Knee",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-63826",
    //   Position: "C",
    //   "First Name": "Boban",
    //   Nickname: "Boban Marjanovic",
    //   "Last Name": "Marjanovic",
    //   FPPG: 0,
    //   Played: 8,
    //   Salary: 3500,
    //   Game: "DAL@LAC",
    //   Team: "DAL",
    //   Opponent: "LAC",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-157804",
    //   Position: "SG",
    //   "First Name": "Keon",
    //   Nickname: "Keon Johnson",
    //   "Last Name": "Johnson",
    //   FPPG: 0,
    //   Played: 1,
    //   Salary: 3500,
    //   Game: "DAL@LAC",
    //   Team: "LAC",
    //   Opponent: "DAL",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-15727",
    //   Position: "SG/PG",
    //   "First Name": "Ben",
    //   Nickname: "Ben McLemore",
    //   "Last Name": "McLemore",
    //   FPPG: 0,
    //   Played: 4,
    //   Salary: 3500,
    //   Game: "DEN@POR",
    //   Team: "POR",
    //   Opponent: "DEN",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-157810",
    //   Position: "PF",
    //   "First Name": "Isaiah",
    //   Nickname: "Isaiah Livers",
    //   "Last Name": "Livers",
    //   FPPG: 0,
    //   Played: "",
    //   Salary: 3500,
    //   Game: "MIA@DET",
    //   Team: "DET",
    //   Opponent: "MIA",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-9589",
    //   Position: "PF",
    //   "First Name": "Udonis",
    //   Nickname: "Udonis Haslem",
    //   "Last Name": "Haslem",
    //   FPPG: 0,
    //   Played: 4,
    //   Salary: 3500,
    //   Game: "MIA@DET",
    //   Team: "MIA",
    //   Opponent: "DET",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-159096",
    //   Position: "SG",
    //   "First Name": "Chaundee",
    //   Nickname: "Chaundee Brown",
    //   "Last Name": "Brown",
    //   FPPG: 0,
    //   Played: "",
    //   Salary: 3500,
    //   Game: "LAL@NY",
    //   Team: "LAL",
    //   Opponent: "NY",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-159097",
    //   Position: "C",
    //   "First Name": "Jay",
    //   Nickname: "Jay Huff",
    //   "Last Name": "Huff",
    //   FPPG: 0,
    //   Played: 1,
    //   Salary: 3500,
    //   Game: "LAL@NY",
    //   Team: "LAL",
    //   Opponent: "NY",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-157823",
    //   Position: "SG",
    //   "First Name": "Greg",
    //   Nickname: "Greg Brown",
    //   "Last Name": "Brown",
    //   FPPG: 0,
    //   Played: 6,
    //   Salary: 3500,
    //   Game: "DEN@POR",
    //   Team: "POR",
    //   Opponent: "DEN",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 1.6,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-145532",
    //   Position: "SG",
    //   "First Name": "Jay",
    //   Nickname: "Jay Scrubb",
    //   "Last Name": "Scrubb",
    //   FPPG: 1,
    //   Played: 6,
    //   Salary: 3500,
    //   Game: "DAL@LAC",
    //   Team: "LAC",
    //   Opponent: "DAL",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0.7,
    //   Ceiling: 1.4,
    //   Floor: 0.5,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 1.4,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-15744",
    //   Position: "SG",
    //   "First Name": "Rodney",
    //   Nickname: "Rodney McGruder",
    //   "Last Name": "McGruder",
    //   FPPG: 1.9,
    //   Played: 7,
    //   Salary: 3500,
    //   Game: "MIA@DET",
    //   Team: "DET",
    //   Opponent: "MIA",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 1.3,
    //   Ceiling: 2.8,
    //   Floor: 1.1,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 2.4,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-157826",
    //   Position: "SG",
    //   "First Name": "Quentin",
    //   Nickname: "Quentin Grimes",
    //   "Last Name": "Grimes",
    //   FPPG: 1.3,
    //   Played: 5,
    //   Salary: 3500,
    //   Game: "LAL@NY",
    //   Team: "NY",
    //   Opponent: "LAL",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0.8,
    //   Ceiling: 1.8,
    //   Floor: 0.7,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 1.6,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-157824",
    //   Position: "PG",
    //   "First Name": "Miles",
    //   Nickname: "Miles McBride",
    //   "Last Name": "McBride",
    //   FPPG: 1.4,
    //   Played: 5,
    //   Salary: 3500,
    //   Game: "LAL@NY",
    //   Team: "NY",
    //   Opponent: "LAL",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 1,
    //   Ceiling: 2.1,
    //   Floor: 0.8,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 1.6,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-157825",
    //   Position: "C",
    //   "First Name": "Jericho",
    //   Nickname: "Jericho Sims",
    //   "Last Name": "Sims",
    //   FPPG: 5.1,
    //   Played: 6,
    //   Salary: 3500,
    //   Game: "LAL@NY",
    //   Team: "NY",
    //   Opponent: "LAL",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 3.4,
    //   Ceiling: 7.4,
    //   Floor: 2.8,
    //   BustPct: 99.9,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 6.9,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-161665",
    //   Position: "SF",
    //   "First Name": "Jamorko",
    //   Nickname: "Jamorko Pickett",
    //   "Last Name": "Pickett",
    //   FPPG: 0,
    //   Played: 3,
    //   Salary: 3500,
    //   Game: "MIA@DET",
    //   Team: "DET",
    //   Opponent: "MIA",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-158853",
    //   Position: "PF",
    //   "First Name": "Chris",
    //   Nickname: "Chris Smith",
    //   "Last Name": "Smith",
    //   FPPG: 0,
    //   Played: "",
    //   Salary: 3500,
    //   Game: "MIA@DET",
    //   Team: "DET",
    //   Opponent: "MIA",
    //   Injury_Indicator: "GTD",
    //   Injury_Details: "Knee",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-158856",
    //   Position: "PF",
    //   "First Name": "Trendon",
    //   Nickname: "Trendon Watford",
    //   "Last Name": "Watford",
    //   FPPG: 0,
    //   Played: 1,
    //   Salary: 3500,
    //   Game: "DEN@POR",
    //   Team: "POR",
    //   Opponent: "DEN",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-145306",
    //   Position: "SF",
    //   "First Name": "CJ",
    //   Nickname: "CJ Elleby",
    //   "Last Name": "Elleby",
    //   FPPG: 1.1,
    //   Played: 7,
    //   Salary: 3500,
    //   Game: "DEN@POR",
    //   Team: "POR",
    //   Opponent: "DEN",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0.7,
    //   Ceiling: 1.6,
    //   Floor: 0.6,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 1.6,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-145305",
    //   Position: "PF/C",
    //   "First Name": "Zeke",
    //   Nickname: "Zeke Nnaji",
    //   "Last Name": "Nnaji",
    //   FPPG: 1.4,
    //   Played: 5,
    //   Salary: 3500,
    //   Game: "DEN@POR",
    //   Team: "DEN",
    //   Opponent: "POR",
    //   Injury_Indicator: "GTD",
    //   Injury_Details: "Ankle",
    //   Tier: "",
    //   StdDev: 0.9,
    //   Ceiling: 2,
    //   Floor: 0.8,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 1.6,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-145310",
    //   Position: "PG",
    //   "First Name": "Saben",
    //   Nickname: "Saben Lee",
    //   "Last Name": "Lee",
    //   FPPG: 4.2,
    //   Played: 5,
    //   Salary: 3500,
    //   Game: "MIA@DET",
    //   Team: "DET",
    //   Opponent: "MIA",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 2.8,
    //   Ceiling: 6.1,
    //   Floor: 2.3,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 5.1,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-161452",
    //   Position: "PG",
    //   "First Name": "JaQuori",
    //   Nickname: "JaQuori McLaughlin",
    //   "Last Name": "McLaughlin",
    //   FPPG: 0,
    //   Played: 1,
    //   Salary: 3500,
    //   Game: "DAL@LAC",
    //   Team: "DAL",
    //   Opponent: "LAC",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-80814",
    //   Position: "PG",
    //   "First Name": "Dennis",
    //   Nickname: "Dennis Smith",
    //   "Last Name": "Smith",
    //   FPPG: 0,
    //   Played: 7,
    //   Salary: 3500,
    //   Game: "DEN@POR",
    //   Team: "POR",
    //   Opponent: "DEN",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-70833",
    //   Position: "PF",
    //   "First Name": "Petr",
    //   Nickname: "Petr Cornelie",
    //   "Last Name": "Cornelie",
    //   FPPG: 0,
    //   Played: 3,
    //   Salary: 3500,
    //   Game: "DEN@POR",
    //   Team: "DEN",
    //   Opponent: "POR",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-14513",
    //   Position: "SF/PF",
    //   "First Name": "Kawhi",
    //   Nickname: "Kawhi Leonard",
    //   "Last Name": "Leonard",
    //   FPPG: 0,
    //   Played: 64,
    //   Salary: 3500,
    //   Game: "DAL@LAC",
    //   Team: "LAC",
    //   Opponent: "DAL",
    //   Injury_Indicator: "O",
    //   Injury_Details: "Knee",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-84674",
    //   Position: "SF/PF",
    //   "First Name": "Kevin",
    //   Nickname: "Kevin Knox",
    //   "Last Name": "Knox",
    //   FPPG: 0,
    //   Played: 3,
    //   Salary: 3500,
    //   Game: "LAL@NY",
    //   Team: "NY",
    //   Opponent: "LAL",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-145351",
    //   Position: "C",
    //   "First Name": "Omer",
    //   Nickname: "Omer Yurtseven",
    //   "Last Name": "Yurtseven",
    //   FPPG: 2.2,
    //   Played: 11,
    //   Salary: 3500,
    //   Game: "MIA@DET",
    //   Team: "MIA",
    //   Opponent: "DET",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 1.4,
    //   Ceiling: 3.1,
    //   Floor: 1.2,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 2.4,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-145358",
    //   Position: "PG",
    //   "First Name": "Markus",
    //   Nickname: "Markus Howard",
    //   "Last Name": "Howard",
    //   FPPG: 1,
    //   Played: 7,
    //   Salary: 3500,
    //   Game: "DEN@POR",
    //   Team: "DEN",
    //   Opponent: "POR",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0.7,
    //   Ceiling: 1.4,
    //   Floor: 0.5,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 1.6,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-159702",
    //   Position: "SF",
    //   "First Name": "Eugene",
    //   Nickname: "Eugene Omoruyi",
    //   "Last Name": "Omoruyi",
    //   FPPG: 0,
    //   Played: 2,
    //   Salary: 3500,
    //   Game: "DAL@LAC",
    //   Team: "DAL",
    //   Opponent: "LAC",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-49115",
    //   Position: "SG",
    //   "First Name": "Wayne",
    //   Nickname: "Wayne Selden",
    //   "Last Name": "Selden",
    //   FPPG: 0,
    //   Played: 1,
    //   Salary: 3500,
    //   Game: "LAL@NY",
    //   Team: "NY",
    //   Opponent: "LAL",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0,
    //   Ceiling: 0,
    //   Floor: 0,
    //   BustPct: 0,
    //   BoomPct: 0,
    //   OwnershipPct: 0,
    //   projminutes: 0,
    //   OptimalPct: 0,
    // },
    // {
    //   Id: "67474-110309",
    //   Position: "SF",
    //   "First Name": "KZ",
    //   Nickname: "KZ Okpala",
    //   "Last Name": "Okpala",
    //   FPPG: 1.4,
    //   Played: 8,
    //   Salary: 3500,
    //   Game: "MIA@DET",
    //   Team: "MIA",
    //   Opponent: "DET",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0.9,
    //   Ceiling: 2,
    //   Floor: 0.7,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 2.4,
    //   OptimalPct: "",
    // },
    // {
    //   Id: "67474-110313",
    //   Position: "C",
    //   "First Name": "Bol",
    //   Nickname: "Bol Bol",
    //   "Last Name": "Bol",
    //   FPPG: 1.3,
    //   Played: 7,
    //   Salary: 3500,
    //   Game: "DEN@POR",
    //   Team: "DEN",
    //   Opponent: "POR",
    //   Injury_Indicator: "",
    //   Injury_Details: "",
    //   Tier: "",
    //   StdDev: 0.9,
    //   Ceiling: 1.9,
    //   Floor: 0.7,
    //   BustPct: 100,
    //   BoomPct: 0,
    //   OwnershipPct: "",
    //   projminutes: 1.6,
    //   OptimalPct: "",
    // },
  ];
  return returnPlayerList;
};